# Say Hello to my docker-compose.yml
# ok. echo "Hello"

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: linkding
      POSTGRES_USER: ${POSTGRES_USER} # read from .env 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # read from .env 
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - linkding_network

  linkding:
    image: sissbruecker/linkding:latest
    restart: always
    depends_on:
      - db
    environment:
      - LD_DB_ENGINE=postgres
      - LD_DB_HOST=db
      - LD_DB_PORT=5432
      - LD_DB_NAME=linkding
      - LD_DB_USER=${POSTGRES_USER} # read from .env 
      - LD_DB_PASSWORD=${POSTGRES_PASSWORD} # read from .env 
      - LD_HOSTNAME=https://bookmarks.mischa.cloud
    volumes:
      - ld-data:/etc/linkding
    networks:
      - linkding_network

  caddy:
    image: caddy:latest # :latest oder :2
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # For HTTP/3
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile # Caddy configuration 
      - caddy_data:/data                      # For certifcates and so..
      - caddy_config:/config                  # For Caddy's internal configuration
    networks:
      - linkding_network
    depends_on:
      - linkding
    environment:
      - NETDATA_USERNAME=${NETDATA_USERNAME}
      - NETDATA_PASSWORD_HASH=${NETDATA_PASSWORD_HASH}

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: my-vps-uptime-kuma
    restart: always
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - linkding_network

  netdata:
    image: netdata/netdata
    container_name: my-vps-netdata
    ports:
      - "19999:19999"
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    networks:
      - linkding_network

networks:
  linkding_network:
    driver: bridge
    enable_ipv6: false 

volumes:
  db-data:
  ld-data:
  caddy_data:
  caddy_config:
  uptime-kuma-data:
  netdataconfig:
  netdatalib:
  netdatacache: